spring:
  application:
    name: taco-cloud
  thymeleaf:
    cache: false
  datasource:
    name: tacocloud
    generate-unique-name: false
    url: jdbc:h2:mem:tacocloud
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    

  